apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ljh-front-shop-main-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ljh-front-shop-main
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 100
      policies:
        - type: Percent
          value: 30
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 50
          periodSeconds: 30
        - type: Percent
          value: 10
          periodSeconds: 15
      selectPolicy: Max
