apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-claim
newName: s3-claim-dev
spec:
  accessModes:
    - ReadWriteMany # supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: "" # required for static provisioning
  resources:
    requests:
      storage: 1Gi # ignored, required
  volumeName: s3-pv-dev
