---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ljh-front-shop-main-secret
spec:
  encryptedData:
    SHOP_HOST: AgBrrIoiO/TB25QvZkQwLaF81A3nuGemB7+zx+SGdMEKvuSVUPEjVGAxFO5PvqY5Xq+f7lIVq5ZyMt1NHD66yhUhgrgU2Q8rFlaanrwitqtn6iPpQMlYE7+eFdH0HN4LodGpnV+o4+tDsfBv0H+PhMEoTdrbngZhHOk/kqfWvKND4ZwzZtkwMhCMGtSMxYETvDH95o2aQbASsLuA2xc2Wi0cfrN1KA+VhmoCtiWQfYkEZrt+wMr3+yQnymgYfRzHU+aNXq4BDGc9mGXr15QHOmjH1tvZw/Ydii5I43Qd4l4Py7iu1sFdQHtKuhX1YoqrGtsTChshxmjYUYe0hiakPwMnTAEa6qA2hEygM074Miv2cZTc4Lk/Js6mGEaC1v4D51/9hcZkKuKszsMzeDsOQhxA4dioKkNrX0EvjP6dGpbrp13ZJ2D1Px70dMtwvJMiQTty0SSBmuVXmG+ePsWNlI7iIsdFWSiCgMXVy/uAM+8oyNXD5w6kVX5ObpMbUGMQx6hNnRpMWBPn10qWZYJdX79jyToTX2LsWE4Exexjh0qaUm//npN2ifGeAMvLQnMHR31lu8ZijJoDoIwHQmac95hyTAbsaavxOXqEVZq3Qp8lQI65VMpWfVGfEyDFtghPnixcuawtATp4F1PUTd65ddph2wcwBsJyLbHT9gu4/l5V65iYKmiSG1gpmZtCl4VzYljR93M=
    SHOP_PORT: AgCY1m3YxdsS9eai7OBOEd+IzRo6tmpLl9cZLfp/L9rrLtkNwcuzkzPXWCYQ63t9qBuQUnqJozvH+WQkkdQ3AonZseTalJHZpaZNZpiUL0fdmQZ3gXAfrtR+tOZeqsMl69LDu/ueeXKmrbz12NgyW9y+4o7M4eKBvA0GtX2cNIQdIPTg8zpoS5IwH4PAacqlB9mTyLUCZnHnd1JHVHQvuMzDD7heXOhZ/wBODaJy+YLFRhSR2+fLAw1kaehUI5gIinfS6NS+xHKlecVgFLyzhQ5edo87NBIT8zmyN3TbjNu6kVfiqdefeeZUnH9j2sQyhx7zW9haHa+VcHLs5y+c+MI/sjfAIRon2KIsJA1ggbzHD43dGizeZRInJj31czhVTBt567l3H/jG7f4qvK/bQ3ozztJbfZ9f4LIA3JPzUyWQkGmYMWmtS/GAmKgincmZfxiXQQacUXvrlD5x6f8FdsIhP/sWsGHgQu8iqlIJ/8Y3bNiqxcPK6g59lNH241hacQUbeBwfVPO79W2nRTJ8/pQZOHxCaJF3ZZ+THaXmzbjFr9pAXkxrSsHAaMKOcC++BXmexLEBzNRNm7Jwd1pdkItYkGjJXAh9m5sm/zTVXKKX5Xi0q6g6iy51/bwnuaj6ajS+z+S/mpw0TSLOU2HpprQT2Bchl8Q9J5l1b10gUsF8QGg/8ATqhtjXdfcz4l9LflqBBpwh
  template:
    metadata:
      creationTimestamp: null
      name: ljh-front-shop-main-secret
      namespace: dev
    type: Opaque
