---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ljh-front-shop-main-secret
spec:
  encryptedData:
    SHOP_HOST: AgCScS3Qxly3jt1ICbPIXCHLmMWX4QORoAyrpeYWWelrkmUym1TrzkF4qdTQBCMs0gd5l7WLEjEKWQOJOfNVkTpy+USUoB/OpMvzAOr8a3HOUMpUFfqxkRxXILF8CnTFAFcM9rf0oH/ops2r+gmCerVOROQngZx0ynPURiPf2A5+ZVEe3oVQlPKZKiI3GeA7FKDNjrXMnz2kqfCPwzNCPnq9sNOxJT/NHaFQiWWG2hoIJY5lb0+PEYeInszCNUaoUIp5S4UwpZmUz0nQLGNR6cMqbek4G/8h8XASlD3YHG/AWkWms+gEn4khIPIXA26cqpSSs8si5uAOJNtkxssRP/BKPser/wuspseKCx3igPJ0uex078pDMoxujJ9zcp/uHtP9/rKCiX63KOLps5st984b8m5XoHVuKi9DFBjDMS971NUYtM0p4pCidIKUsjKbcHMgP40jH6BKo4SYIrD9wITgtnrLSNr3TXA4BPNEC1B9ADzhu3yIAsViRHQC8ANajgxTOcHPQMDM+k/qNu6DuQnOiWsXoKeeGnM6RUDADWFdvb6c/ZTjJZtb7xl6aGdZwrQTcJWKMyvnEERI6iu5nzZ8/XB2jeA7WNIE7Ocr8AurjoiwMeQVAKvADsGUXIMgQVIRE3CFGI1wUvEC2KaU045erbPMtoRbqiFCj6TWMZWTWxrRCJvYGDDCkcYxufPXyUpLHyx1LCp4fG7j
    SHOP_PORT: AgAMG4A0fw7oLNQbrknmtdfuCBeVgtTydZQefuYvVtFbI4eUOHK4wcYAfUxsHpf8apr7PkL4bUcsCObyhZXN4Hw2Gq1a/sKx7PjIzQng9nyCjMsLd5kQKwsiOOuynQQLUGFj4vpXvjRmnb52DrgJSQlsnr/Ysk9gEZ/CZ1pUaUp5AS3L1nUjxClkwxzs3ggzDRVRKbJvmgPk1inCUrTKeOCNNJML7N2+gWqFoR04tzlDOYBGbLRE9CnXCp6Q4+/E0jbvHI+ongNj1ZslmlOThvBNMnr8n6A0UTyJ5YV1tPKuqq9B1FbVWpc54bpDgL1Ri/qqT5XjEZsWB4tiJUlJufPC/P2OgVB+ITI7tKZKu78xmqx5gp7S66kGvfnA0HBP85par8QpXbA0/kWzoa+pJuOFb104T/eKspx68sSCD5IR3csBGxPrGPKpDliMSzj9uxslJcApd9p2QWtwIVoo/MChIWt+zAZHbW+IASQuSNIYUbn5qedqduULt2JAi53UgawXsPIg/fRMgMAmOGP3VWyXp6IaUNs1SAESHXfj3g5HSUL2QskJevpReIIVOC5HZnnCY9YC3kDUERedICK01sFOAZ5X2Rv1YevJen3Gb70txsyAHRZx0NmGzTr/aoWIUXop59iWxnLOFcASuuRLe+4CIzW8nQCg4A8J8FCXYtNsMZlCPYWcRxW4yNtaHU2b3/H+Afin
  template:
    metadata:
      creationTimestamp: null
      name: ljh-front-shop-main-secret
      namespace: dev
    type: Opaque
