---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ljh-front-shop-main-secret
spec:
  encryptedData:
    SHOP_HOST: AgCzsvPFZzjJYyolyKXDCDEvdu6ZZTUh8qLrO6x5UgfkPCEYjIc4MotEjQg8kcujCgCTz9dqxbgydDhqDhn4SmgUCEJuzQD+hrhzC5CL0SsicOUyByhUwF1nTE9may57/t8hz9S5X+1JdPvCPDsN0gPglJV8x8lB7X0oloST9FWLug45ijWjzBdM909vDGKioAhNJvqQ4QAUbYvqlth8ykThkwG4RNEKDgeWtcOtTxX1n9ExZ16Hr8nWERVtiCn1gD82pewChQHoCCOUW4nJYmMW610bFVM9bSjXCsYmNWsORqs/f61RdEo1B+CSCyIr+nc9ZTAIg8QFj/r5AcGGVN/x+2PLQukF7ckQ1w9aT4zy38X9DCbkPhXZX7hV4FZncpkH3EzMpLYHoZqo8lTsJ9BIu2E/wk/iysifEDDxlbQCJTg1ola42j5IiDd+3icntsr0g7wvBel/vgFtuRRsGMjkanA3s36X5H/Khm78U35B8vS0X6cYBvZfbNlPETvnVL7QxE7S1/ZVucQzW6N2n+G0qEgP4xMm75d9icMlP279nQn+uUuFkgN8T8W/l5ZtCJvctyZdJOpXvFRImKwR1wAmH31VamYh/4v6YYFe+9GCx4MFhnvnHKMfz2Vw7kQIrVQEtw2GB70j/b2RX5y7ee0Ik6ASnp649OUrcUbkXlcnVPMMI3/uZAfVkqfozXvsxv8j/rQ=
    SHOP_PORT: AgAZBHbvxDqt/xZtEBmjXO9JgD5rfG+O4285FmsX9xVS9zltkTwrvk/MRhhRHxF8VwOMekWrjGuyPV/FZ0A8oIepUSHF5yDTb3ffRcEDSB2ICb1uIxqHSGNqMtdltn/f0PLhrfKxjUGeHkAqzFD0ZHMkYwA8A7GRM9zQHcQ7hXBhLtRTGBPmeheShW2rWlNbAsHbAWHPMAvdNcjee6/xp+tkmzd1Q1QUZJ0naUcS06Vl3eFe6KnF4nSbAHMmbT9+ksqVyDmudH1TeKUTXOhMkc10vGhMZTB2pcYzeKHag3CuQhzcobSpEuAFALF4poMMuUNXmk7u6PleB8hfuPzlYxWhtlxL4GbsBGYwU/L+oc4rmqYs0y2fIU+reoXqRZaZRUReSwpg6oJBEnJXcrTcoDXPj1uDgGyh+t9v+guK4VqvhtRXqNm77RJkiNTM3mb1XX9mpytiPwh6m82UTFpyxOI0n88M5Q5uXH1zFQ2teQBoQLbC/zVWHUdz03qPhKoFiHiwWgwsEUhFXM6QfyVjNrmvD0DhgRealTEeKb4XxyJdI3Wwjw5FqOcl1UJMfSU+fEBLMB3jfOpciOBL9rFdFZDSS32Kf0QS/mqL66X4a+P1RtG7gfJgCvIqXCGDLqw8Yer5d4+lbc3Q7z+HR6us6vpAcKUYJBIs51o1eO7vz5JdYd7JEWEfcFPV+vIUizSJsZhNNXJl
  template:
    metadata:
      creationTimestamp: null
      name: ljh-front-shop-main-secret
      namespace: dev
    type: Opaque
