---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ljh-front-shop-main-secret
  namespace: prod
spec:
  encryptedData:
    SHOP_HOST: AgA2Q6NGgzP3It2RCw4qASsQQP5OenRiWkA1N9Mkp1srT/L8HSnWg7A+eEIcbR1IAx9NqpeAze0lD8R99TxcX7G5Cz5GzZE3Tnvs3hArIcPm1AP8U1h2r1QhvzlGTD6aYfNCAzFO4Q1vt3O8Qg1p7f1ZFNrakB/XD1M1e2BlMBgEMsHANveS8/9pLLjYfLIdT/CM0rxvEPN9dcOPUcDpDNb+vho56Cak8+qtsrOFL6ZaNArfz53Mt2Uon2NQgd0+MDEv1GxQPdLooRrvSFewHRRBiLjZgKq+zkAIzwLKKCLbs+tg9tTZCRhH0l07GNn+iFknyCegJvB5/qqJvjdYQVfu/8pftNytQl/MMFTh8F6bRWGn0Z682bHA+WRXFlb9wxuw40urIqKwVxa5sEGKRStQwIOYvvhOEbeLJsXv/LEBvu5sf9QquP3zyPrrG7x+UNwFqZlqVtAkmGUgWmGwRJXsV/4lgX5N1VKfIIWqNIM0eBrYC1C1ncv9azoddgU+CpcgQhUSN7Gm5uk9hZ6y7OtSgj2Z/B3IbdkpfygmSefI0Cf3ls9EVbM8CEilz27eabT8JrqgMe+Cyp1zNRUWA8252+6Z45J8koDY2djDI/g4UwjxG1ryZ0ELNopeypjGj3eqvhoQx9zGC8t0En+ufoyP4jq0CtHREM48coO4ywTjDQmZ4TqKL+ulSqex6LpKCvwCIoc=
    SHOP_PORT: AgA8lCMYCX/rYZjll9w8gaST15mF/XPDSW2gc/70TX2tx4nRjAlYjLKqgdoD0yruP5Cj1hgJFSyi9xf/7f1rDxnbuHRBshnqtlrF/tVXU2CaZaq8qgw5QixnGO/SjwFk/ixzuPs5sANuQHx9DlXXj/q8+D2HIKgARCKZQ8KhBqoRBzTYWvZHCwtmLVsYC6bMWNnMoxEA70EGV2C8iIhK2mLmhd++4/yoJZGiypFm3fz/LbHjvfeRGicaLCcSj1YrVlGT6iZ5IQNqa+WwOTig13bv/FrjHnqF3rRRcmPSfjFI4w65q5K+j6WRASYl9hnPZPmf/VBJr6q/1YohkZlBhqB0SR1xRw5asfzb0ulQDE+ZDH9T7u7MAPC0eVWHvsm3uW/36xsYkJFOswKGWdU7Ca1CbXG9Zhbyn3Vm+Y/7mwjHhXgv7FRrwDmfnXBYI3c5MqpkElW+VLu+wIIsxuycm1FWaPp+3E9cyGFkhyXS/n1eHbq3PFjy6lgT1RNleSDbfApiien3oU5MzrXdjreMASt2GQ6rnyc62Rli/f2O3tZvzM1bEVMmQle1Eu0HQOOgBx332oueNDX8J00GWGxwCQg16xhiWEjHKBw0O/wEcoCXaEJRot4JIFj7daMe7dBKlbhovVaDv5/5U4FZIuT3tDkjyHwGJcKV42vGKb48NQBK1/Dh0e5VI5lgWRpa0fAU+D2GInqr
  template:
    metadata:
      creationTimestamp: null
      name: ljh-front-shop-main-secret
      namespace: prod
    type: Opaque
