apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: ljh-front-shop-main
spec:
  replicas: 10
  selector:
    matchLabels:
      app: ljh-front-shop-main
  template:
    metadata:
      labels:
        app: ljh-front-shop-main
    spec:
      containers:
        - name: ljh-front-shop-main
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - name: persistent-storage
              mountPath: /usr/share/nginx/html/images
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: s3-claim
