apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../base
  - ljh-front-shop-main-pv.yaml
patches:
  - path: deployment-patch.yaml
  - path: active-patch.yaml
  - path: preview-patch.yaml
  - path: hpa-patch.yaml
  - path: pvc-patch.yaml
  - path: ingress-patch.yaml
  - path: SealedSecret.yaml
