---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ljh-front-shop-main-secret
spec:
  encryptedData:
    SHOP_HOST: AgABqaJU/2Vhn2FpM8F524HYobuLwZkUooJFQejPt4g1BUMA/g1u04APwRWKURDlUqzgVDgqVQ4TwXuOI2izlpdLNWSMj7GItOoPqG0VPBjNirzy1MRw3UXtJlMEgpt1NdtElgnx79/Jfk2YH75D1EsWJIli0dYnshM7B8DYd+hwndrAfXVAoc3tyVT0rN4uwtXSKBqOGRZQ0YSPLhZWMJI4x90wecVNzCMAJKItwLubobMSWigui0Gzt4JZJf+VI5t3WIMJPxaE8qWwULc4+ogBhYdau5S87G4N33UQHYL74rlE10sb5De3F2sM2rdZ+Y/pxBkIk4m+IUBVzODu0vENcHLuPUNUasUpQVpth6gm/GCpvt3Yyfh1naspttmgLgPhjA3kgo+zRuCuVmIVFQhFNdcPfYsJynlx3YVLWrvy3xdgH0jKGncFVQVLQRd5oueuO0LZtbSw7QhXKobwRZQPW5VSM+fQsHy76sHpp1+XRoE0qJRNK6IWVXI+cSSm+4JHgEGCq8F+LcQ9xi5lAcOmDV+ohI/gG0+QEOZUS2kmcwio9XS9kNFxVeZTmbTdMXsOxWH065kBRsTrgolLfFGgxvE81KrzOUTR90E3Ksz8ilLn/VTQUKiKko5UsZpGf8CHQeZ+QNWwMprViO3nriJAQ/cyPNmAWt6p/BTtMOsH1NnnAvW/YEEK6HO8K9d+w2lc7AE=
    SHOP_PORT: AgC+iCfGM3L6sWmp5V4QrOA1/RFFkjnqZiAwZ6UaaWfWkz6AuTvpLFMTnC4YR4REbXR7LUnxcE+RtY/sosH0FZzHgLOn64V39VEFqAlAmjLCA/qKcle28KgUOA/98yMFlTDecy4T4P0zXi5BIGI7nDa0ndhJtS+KyUIa4Tq2b0N9ajMGB44hvEmsjp0AvGL3vLil78zqv+unYC6sP1NHKelpq8SHQJyktGrLjqxYmgfpB1J2BqkjbcoTYCqhb35iisYNup7O8TtdC3qOo1kYmsS9QuuO1BLIpnLTgu86MBULMfSRRKMGM2iCWd3Qq8oekDco+pFYf3ZLLMGkjeTG+ad4J+O2xe+TvF4Obma2YoSPSrSejYny2sKNXVWd2Dd9hx1uupHuE3TI74AtuHrfpUY+YNz+23fy2hiNeyPLlUmmPV00805gtzQX0KjaN7ZJd8ubCjPxPsTX9kwS+nEBjE41aOFb6TphgglaBXuwpdTCMt8Fj0JRk9iK2NPy1ZiIv5nNO0BYuNl7GQzB4KmN1qT6hIJTQ7ZvnK/3h9BeEiBUGZqjjGkTsSZaYg/LyKardVxIWJ+s4fK6mZEmt8LOYddMdYTc7b1wZF+JHRtGXnACvHzRjFe/mSSnkC4LKlI6nanNRkYOX3a+fHbHR6A2/WQqlQuFQTbeSSZr6x4eVFCTEwwTIhNb/19G6y/Vl3ZjlXq4CoDy
  template:
    metadata:
      creationTimestamp: null
      name: ljh-front-shop-main-secret
      namespace: prod
    type: Opaque
