apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ljh-front-shop-main-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ljh-front-shop-main
  minReplicas: 10
  maxReplicas: 40
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 30
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 70
          periodSeconds: 30
        - type: Percent
          value: 10
          periodSeconds: 15
      selectPolicy: Max
