apiVersion: apps/v1
kind: Deployment
metadata:
  name: ljh-front-shop-main
  namespace: default
spec:
  replicas: 10
  selector:
    matchLabels:
      app: ljh-front-shop-main
  template:
    metadata:
      labels:
        app: ljh-front-shop-main
    spec:
      containers:
        - name: ljh-front-shop-main
          image: 654654416925.dkr.ecr.ap-northeast-1.amazonaws.com/ljh-front-shop-main:v1.0.0
          envFrom:
            - secretRef:
                name: ljh-front-shop-main-secret
          resources:
            requests:
              cpu: 400m
              memory: 128Mi
            limits:
              cpu: 400m
              memory: 128Mi
          volumeMounts:
            - name: persistent-storage
              mountPath: /usr/share/nginx/html/images
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: s3-claim
